# Copyright 2023 Eric Smith
# SPDX-License-Identifier: GPL-3.0-only

Import('env')
env.Append(CXXFLAGS = ['-g', '--std=c++20'])

env.Tool('qt6', toolpath = '.')
env.Tool('otf_to_c', toolpath = '.')

env.EnableQt6Modules(['QtCore',
                      'QtGui',
		      'QtWidgets'])

font = env.File('Aileron-Bold.otf')
font_c = env.OTF_TO_C(font)
font_h = env.OTF_TO_H(font)

SOURCES = [font_c,
           'main.cpp',
           'main_window.cpp',
	   'central_widget.cpp',
	   'g_hex_line_edit.cpp',
           'g_lcd.cpp',
	   'g_lcd_annunciator.cpp',
           'g_lcd_digit.cpp',
           'g_lcd_segment.cpp',
           'g_lcd_view.cpp',
	   'g_registers.cpp',

	   'lcd.cpp',
	   'lcd_registers.cpp',
	   'lcd_mapper.cpp']

env.Program('voyager-lcd', SOURCES)
